### PR TITLE
Add Tox support

### PR DESCRIPTION
**Pull request by FedericoCeratto**
Related to PR #23

### CODE REVIEW

**Comment by commandline** [comment]
It has been a while since I hacked on any Python projects--can you provide some context on Tox, maybe a link?

**Comment by FedericoCeratto** [comment]
https://tox.readthedocs.org/en/latest/
Tox is a popular tool to run tests in dedicated virtualenvs. Particularly useful if you want to test code against different libraries or different interpreters in an isolated Python environment.

**Comment by commandline** [comment]
Makes sense. Would you want to add tox.ini, then, to the package data exclude to keep it out of the distributed package?

**Comment by FedericoCeratto** [comment]
The tox.ini file is not being included in the source or binary tarballs.
(CREDITS.txt and COPYING.txt are also not being included)

package_data is very misleading:
http://blog.codekills.net/2011/07/15/lies,-more-lies-and-python-packaging-documentation-on--package_data-/

**Pull request merged**
